# Generated by Django 2.1.2 on 2018-10-20 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, default=True, max_length=254)),
                ('dateofjoining', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('duration', models.DateTimeField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('customers', models.ManyToManyField(to='form.Customer')),
            ],
        ),
    ]
