# Generated by Django 2.1.2 on 2018-10-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20181020_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
