# Generated by Django 2.1.2 on 2018-10-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20181021_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='room_number',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Customer'),
        ),
    ]
