# Generated by Django 2.1.2 on 2018-10-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20181022_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
