# Generated by Django 2.1.2 on 2018-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20181024_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='checkout',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
